### ISSUE TITLE
Unable to find libclang

### ISSUE THREAD

**Issue by dbeyter** [pjedge/longshot#33] opened 2019-12-09 14:14 UTC
Hi Peter, 

I've been trying to compile this using cargo, though I am having this problem where it complains not being able to find libclangAST.so.7 even though it exists.

AR_x86_64-unknown-linux-gnu = None
AR_x86_64_unknown_linux_gnu = None
HOST_AR = None
AR = None
running: "ar" "crs" "/home/username/tools/longshot/target/release/build/rust-htslib-007e912aeb150570/out/libwrapper.a" "/home/username/tools/longshot/target/release/build/rust-htslib-007e912aeb150570/out/wrapper.o"
exit code: 0
cargo:rustc-link-lib=static=wrapper
cargo:rustc-link-search=native=/home/username/tools/longshot/target/release/build/rust-htslib-007e912aeb150570/out

--- stderr
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib64/clang-private/libclang.so.7 could not be opened: libclangAST.so.7: cannot open shared object file: No such file or directory"', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by pjedge** [comment] 2019-12-10 18:51
It seems that the problem is with building rust-htslib. Unless you are interested in forking/developing Longshot I recommend just doing the conda installation so this isn't an issue. Otherwise, maybe you can try setting LIBCLANG_PATH as described in this similar issue? https://github.com/rust-bio/rust-htslib/issues/112

**Comment by pjedge** [comment] 2020-01-02 22:15
issue resolved by using conda

**Closed by pjedge** 2020-01-02 22:15 UTC
