### ISSUE TITLE
question about haplotype bam files

### ISSUE THREAD

**Issue by caonetto** [pjedge/longshot#27] opened 2019-05-02 04:13 UTC
Hi, I am currently trying to phase a diploid genome assembled with nanopore data
and Ive been playing around with longshot. Everything looks good until now, I was just wondering what is the actual output of the phased bam files. Are this containing only the phased block or the actual reads associated to the complete haplotype, including common regions between both haplotypes? I ask this cause I have the intention of extracting those reads and reassembling every haplotype indepdendently.

Thanks for your time.

**Comment by pjedge** [comment] 2019-05-02 18:00
The haplotype-assigned bams are obtained by taking each read and calculating the probability that it came from either haplotype, based on the phased alleles found in the output VCF.
Reads that can be confidently assigned go in <prefix>.hap1.bam or <prefix>.hap2.bam, while the reads that fall below the --hap_assignment_qual go in <prefix>.unassigned.bam.
Currently, the phase block that a read belongs to is not annotated. I.e, if there is a large unphaseable gap with two independent phase blocks on either side, the reads assigned to Hap1 for each block will be written to the same file and similarly for Hap2. Even though in real life, those reads are not confidently phased to one another. But, you could infer what block a read belongs to based on the PS annotations in the corresponding VCF (I.e. figure out the boundaries of SNVs with a specific PS annotation, and then extract that region from the phased BAM file)

**Comment by caonetto** [comment] 2019-05-02 22:08
Thanks for your quick response Peter.
Ok, so if I understand you well, in theory to try and re-assemble each haplotype independently , lets say H1, the reads to use should be the H1.bam reads combined with the unassigned reads?

Thanks.

**Comment by pjedge** [comment] 2019-05-02 22:13
no -- the unassigned reads contain a mixture of H1 and H2, they just didn't have enough evidence to confidently assign one way or the other.

**Comment by caonetto** [comment] 2019-05-02 22:14
Thanks for clarifying.
Thanks again.

**Comment by pjedge** [comment] 2019-05-02 22:16
To re-assemble independent haplotype for H1 just use the H1.bam. Just keep in mind that close range information is good (i.e. reads in the bam that are near each other on the chromosome are probably from the same haplotype), but the long-range information is probably not good (reads that are far away from one another on the chromosome may or may not be really from the same haplotype).

**Comment by pjedge** [comment] 2019-05-02 22:17
anytime -- good luck!

**Comment by baishengjun** [comment] 2019-10-31 02:31
Hi, I have some errors following this ,how to solve it ?
2019-10-30 22:24:30 Min read coverage set to 6.
2019-10-30 22:24:30 Max read coverage set to 8000.
2019-10-30 22:24:30 Estimating alignment parameters...
[E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes
error: Error estimating alignment parameters.
caused by: Error reading BAM record.
caused by: truncated record

**Comment by pjedge** [comment] 2019-11-24 19:02
@baishengjun Your issue does not seem to be related to the haplotype bam separation feature. Nonetheless, I'll try to answer. Can you verify that the bam is not corrupted? I've had errors similar to the one you describe and it is often a result of corruption. And would it be possible for you to create a shareable minimal example file that reproduces the issue?

**Closed** 2020-02-05 17:43 UTC
